version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- pwsh: dotnet build -c Release

after_build:
- pwsh: .\pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: ElAeMRSkpq3xUZ1TbenrrObh1zB/p62I5ICs92heJnTvkcl4Znc5o36vCyqcOK49
  on:
    appveyor_repo_tag: true
